CREATE DATABASE java CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON java.* TO usrjava@'%' IDENTIFIED BY 'Java123*522' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE java;


CREATE TABLE AGENDA (
  id INT(3) AUTO_INCREMENT,
  linea VARCHAR(200),
  PRIMARY KEY (id)
) ;
